In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [4]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [5]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [6]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1641 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 7ms/step - loss: 0.1640 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 6ms/step - loss: 0.1636 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1635 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1637 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1631 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1628 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1627 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1625 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1627 - accuracy: 0.9800


In [7]:
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

1/1 [==============================] - 0s 99ms/step
[[9.98867154e-01 1.13278686e-03 1.37533419e-07]
 [9.95566070e-01 4.43280721e-03 1.11739621e-06]
 [9.97918665e-01 2.08084378e-03 4.31141046e-07]
 [9.95236218e-01 4.76215454e-03 1.62271101e-06]
 [9.99111474e-01 8.88381037e-04 1.05371555e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [8]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

1/1 [==============================] - 0s 28ms/step
[[8.5506650e-07 1.4216278e-01 8.5783631e-01]
 [2.3166508e-06 2.2018649e-01 7.7981114e-01]
 [4.1359726e-06 2.4641636e-01 7.5357956e-01]
 [9.9450767e-07 1.1001884e-01 8.8998020e-01]
 [1.1213764e-05 2.8402397e-01 7.1596479e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
